"""make_map.py - build mapdata.js (window.MAPDATA) for the explorer world map.

Source: Natural Earth 1:110m land polygons (public domain, naturalearthdata.com).
    curl.exe -L -o %TEMP%\\ne_110m_land.geojson ^
      https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson
    python make_map.py [path-to-geojson]

Projection: Miller cylindrical (looks like a classic wall map and fills a 16:9 sheet better than
equirectangular). Coordinates are written in "sheet units": x 0..MW, y 0..MH, where the sheet shows
lon -180..180 and lat LAT_TOP..LAT_BOT. map.js repeats the same maths (MX/MY) for pins and the route,
so keep the constants in sync with map.js.
"""
import json, math, os, sys

MW = 600.0          # sheet width in virtual units (the stage is 640x360)
LAT_TOP, LAT_BOT = 82.0, -58.0
EPS = 0.22          # Douglas-Peucker tolerance in sheet units
MIN_AREA = 0.6      # drop specks smaller than this (sheet units^2)


def miller(lat):
    return 1.25 * math.log(math.tan(math.pi / 4 + 0.4 * math.radians(lat)))


Y0, Y1 = miller(LAT_TOP), miller(LAT_BOT)
K = MW / (2 * math.pi)
MH = (Y0 - Y1) * K


def proj(lon, lat):
    lat = max(-85.0, min(85.0, lat))
    return ((lon + 180.0) / 360.0 * MW, (Y0 - miller(lat)) * K)


def dp(pts, eps):
    """Douglas-Peucker on an open polyline (iterative)."""
    if len(pts) < 3:
        return pts
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        a, b = stack.pop()
        ax, ay = pts[a]; bx, by = pts[b]
        dx, dy = bx - ax, by - ay
        L = math.hypot(dx, dy) or 1e-9
        best, bi = -1.0, -1
        for i in range(a + 1, b):
            px, py = pts[i]
            d = abs(dy * px - dx * py + bx * ay - by * ax) / L if L > 1e-9 else math.hypot(px - ax, py - ay)
            if d > best:
                best, bi = d, i
        if best > eps and bi > 0:
            keep[bi] = True
            stack.append((a, bi)); stack.append((bi, b))
    return [p for p, k in zip(pts, keep) if k]


def area(r):
    s = 0.0
    for i in range(len(r)):
        x0, y0 = r[i]; x1, y1 = r[(i + 1) % len(r)]
        s += x0 * y1 - x1 * y0
    return abs(s) / 2


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.environ.get('TEMP', '.'), 'ne_110m_land.geojson')
    with open(src, encoding='utf-8') as f:
        gj = json.load(f)
    rings, n_in, n_out = [], 0, 0
    for feat in gj['features']:
        geom = feat['geometry']
        polys = geom['coordinates'] if geom['type'] == 'MultiPolygon' else [geom['coordinates']]
        for poly in polys:
            for ring in poly:
                n_in += len(ring)
                if max(p[1] for p in ring) < -55:      # Antarctica: antique-map style leaves it off
                    continue
                pts = [proj(lon, lat) for lon, lat in ring]
                if pts[0] == pts[-1]:
                    pts = pts[:-1]
                # split the ring at its point farthest from the start so DP keeps both halves
                far = max(range(len(pts)), key=lambda i: (pts[i][0] - pts[0][0]) ** 2 + (pts[i][1] - pts[0][1]) ** 2)
                s = dp(pts[:far + 1], EPS)[:-1] + dp(pts[far:] + [pts[0]], EPS)[:-1]
                if len(s) < 3 or area(s) < MIN_AREA:
                    continue
                n_out += len(s)
                rings.append([round(v, 1) for p in s for v in p])
    rings.sort(key=lambda r: -len(r))
    out = {
        'src': 'Natural Earth 1:110m land (public domain)',
        'mw': MW, 'mh': round(MH, 2), 'latTop': LAT_TOP, 'latBot': LAT_BOT,
        'land': rings,
    }
    js = '// generated by make_map.py - Natural Earth 1:110m land (public domain), Miller projection\n'
    js += 'window.MAPDATA=' + json.dumps(out, separators=(',', ':')) + ';\n'
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, 'mapdata.js'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(js)
    print(f'rings={len(rings)} points {n_in} -> {n_out}  sheet {MW:.0f}x{MH:.1f}  bytes={len(js)}')


if __name__ == '__main__':
    main()
